#!/bin/bash

# This is a thin wrapper around ltsoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using ltsoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_LTSOIND

# Grab the value of $REAL_LTSOINCLI which may be ltsoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_LTSOINCLI}" "$@" | sed 's/\r//'
